language: python 
sudo: enabled
install:
  #- pip install -r requirements.txt
  python -mpip install --upgrade -r optional-requirements.txt
  #python -mpip install --upgrade -r requirements.txt
  npm install
script: 
    python -mpytest